name: Docker Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and start Docker containers
      run: docker-compose up --build -d

    - name: Run tests
      run: |
        # Add your test commands here
        echo "Running tests..."
        # Example: Wait for services to be ready
        sleep 30
        # Example: Check if backend and frontend are running
        curl --connect-timeout 20 -f http://localhost:8080/health && curl --connect-timeout 20 -f http://localhost:3000/health

    - name: Cleanup
      run: docker-compose down